### ISSUE TITLE
Challenge 3 - pin layout

### ISSUE THREAD

**Issue by kxynos** [tjclement/bolt-site#2]
Hi Tom, I think you need to warn the users that the labels SCL and GND on the Challenge Board - 'Bolt Target: Level 1' should be considered as swapped. The pin layout is SCL, SDA and GND. I am not sure how you want to update the guide to show this problem.

**Comment by tjclement** [comment]
Added a warning for this in the Target board docs. Thanks for giving a heads up about this, and sorry for the inconvenience.. We'll make sure it's patched in the next revision 👍
